# Generated by Django 3.0.14 on 2022-05-05 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=40)),
                ('prenom', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateOperation', models.DateField()),
                ('montant', models.FloatField()),
                ('type', models.CharField(max_length=40)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krekermarouane.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40)),
                ('dateCreation', models.DateField()),
                ('solde', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krekermarouane.Client')),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='krekermarouane.Operation')),
            ],
        ),
    ]
